kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      city: seffner
  template:
    metadata:
      labels:
        city: seffner
    spec:
      containers:
      - name: nginximage
        image: krishchan3/nginx:latest


---
kind: Service
apiVersion: v1
metadata:
  name: nginx-sa
spec:
  selector:
    city: seffner
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32110
  
